### ISSUE TITLE
customTransformers 执行报错

### ISSUE THREAD

**Issue by l5oo00** [max-team/ts2php#96]
发现自定义的 customTransformers 执行会报错， 貌似是 ts2php 内置的 transformer 会破坏原 ast 的结构， 导致自定义的 transformer 里遍历 ast 会报错， 用的是 ` ts.visitEachChild` 来遍历。

猜测是这里的处理有问题：
https://github.com/searchfe/ts2php/blob/f511257b223c2366881acdc0577f5f37791f89fd/src/transformer.ts#L215

报错时正在处理这一行源码： `const {name, data, outputData} = originalParams;`

报错的 node 如下：
![image](https://user-images.githubusercontent.com/1233234/69625069-cc706e00-1080-11ea-9c5a-248b0dab2eb5.png)

报错的调用是： `node.getChildCount()`

错误堆栈：
```
internal/process/warning.js:18 (node:56266) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'text' of undefined
    at createChildren (/Project/node_modules/typescript/lib/typescript.js:120256:65)
    at NodeObject.getChildren (/Project/node_modules/typescript/lib/typescript.js:120219:56)
    at NodeObject.getChildCount (/Project/node_modules/typescript/lib/typescript.js:120212:25)
    at SanIdTransformer.visitor (/Project/ts2phprc.js:105:27) // 在这里调用的 node.getChildCount()
```

**Comment by meixg** [comment]
可以发下要转换的代码，以及 transformer 的代码不
